# Simulating Coin Flips

**np.random.randint(startnum, endnum(excluded))**

**np.random.choice([a list of number to randomly generate], size=number to repeatly generate, p=[every number's probability in before list])**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
# outcome of one coin flip
np.random.randint(2)

0

In [3]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([0, 0, 0, ..., 1, 0, 0])

In [4]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.4926

In [43]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [18]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 0, 1, ..., 0, 0, 0])

In [24]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4945

In [28]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.2, 0.8])

array([1, 1, 1, ..., 1, 1, 0])

In [37]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.2, 0.8]).mean()

0.8017